[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
meta_amm = "CzVBvCUvx8RWEsiRybEAtr6TwydEn9WByXG7WTezGsq1"

[programs.devnet]
meta_amm = "CzVBvCUvx8RWEsiRybEAtr6TwydEn9WByXG7WTezGsq1"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
