[workspace]
members = [
    "crates/meta_amm_config",
    "crates/meta_amm_math",
    "crates/meta_amm_sim",
    "programs/meta_amm",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
anchor-lang = "0.32.1"
meta_amm_config = { path = "crates/meta_amm_config" }
meta_amm_math = { path = "crates/meta_amm_math" }

[profile.release]
overflow-checks = true
